// Code generated by protoc-gen-go. DO NOT EDIT.
// source: robot_protobuf.proto

package protobuf

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//查询用户是否在线
//message UsersOnlineReq{
//   string clientId = 1;
//}
type Rsponses struct {
	Code                 int64    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg                  string   `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	MsgId                int64    `protobuf:"varint,3,opt,name=msgId,proto3" json:"msgId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Rsponses) Reset()         { *m = Rsponses{} }
func (m *Rsponses) String() string { return proto.CompactTextString(m) }
func (*Rsponses) ProtoMessage()    {}
func (*Rsponses) Descriptor() ([]byte, []int) {
	return fileDescriptor_da0d343210858f0d, []int{0}
}

func (m *Rsponses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Rsponses.Unmarshal(m, b)
}
func (m *Rsponses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Rsponses.Marshal(b, m, deterministic)
}
func (m *Rsponses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Rsponses.Merge(m, src)
}
func (m *Rsponses) XXX_Size() int {
	return xxx_messageInfo_Rsponses.Size(m)
}
func (m *Rsponses) XXX_DiscardUnknown() {
	xxx_messageInfo_Rsponses.DiscardUnknown(m)
}

var xxx_messageInfo_Rsponses proto.InternalMessageInfo

func (m *Rsponses) GetCode() int64 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Rsponses) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func (m *Rsponses) GetMsgId() int64 {
	if m != nil {
		return m.MsgId
	}
	return 0
}

//上报机器人数据
type UploadReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ToClientId           string   `protobuf:"bytes,2,opt,name=toClientId,proto3" json:"toClientId,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Location             string   `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	ChargeState          int64    `protobuf:"varint,5,opt,name=chargeState,proto3" json:"chargeState,omitempty"`
	BatteryLevel         int64    `protobuf:"varint,6,opt,name=batteryLevel,proto3" json:"batteryLevel,omitempty"`
	CurrentTask          int64    `protobuf:"varint,7,opt,name=currentTask,proto3" json:"currentTask,omitempty"`
	DeviceId             int64    `protobuf:"varint,8,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadReq) Reset()         { *m = UploadReq{} }
func (m *UploadReq) String() string { return proto.CompactTextString(m) }
func (*UploadReq) ProtoMessage()    {}
func (*UploadReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da0d343210858f0d, []int{1}
}

func (m *UploadReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadReq.Unmarshal(m, b)
}
func (m *UploadReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadReq.Marshal(b, m, deterministic)
}
func (m *UploadReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadReq.Merge(m, src)
}
func (m *UploadReq) XXX_Size() int {
	return xxx_messageInfo_UploadReq.Size(m)
}
func (m *UploadReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadReq proto.InternalMessageInfo

func (m *UploadReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *UploadReq) GetToClientId() string {
	if m != nil {
		return m.ToClientId
	}
	return ""
}

func (m *UploadReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UploadReq) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *UploadReq) GetChargeState() int64 {
	if m != nil {
		return m.ChargeState
	}
	return 0
}

func (m *UploadReq) GetBatteryLevel() int64 {
	if m != nil {
		return m.BatteryLevel
	}
	return 0
}

func (m *UploadReq) GetCurrentTask() int64 {
	if m != nil {
		return m.CurrentTask
	}
	return 0
}

func (m *UploadReq) GetDeviceId() int64 {
	if m != nil {
		return m.DeviceId
	}
	return 0
}

//上报机器人位置
type UploadLocationReq struct {
	ClientId             string   `protobuf:"bytes,1,opt,name=clientId,proto3" json:"clientId,omitempty"`
	ToClientId           string   `protobuf:"bytes,2,opt,name=toClientId,proto3" json:"toClientId,omitempty"`
	Action               string   `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	Word                 string   `protobuf:"bytes,4,opt,name=word,proto3" json:"word,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UploadLocationReq) Reset()         { *m = UploadLocationReq{} }
func (m *UploadLocationReq) String() string { return proto.CompactTextString(m) }
func (*UploadLocationReq) ProtoMessage()    {}
func (*UploadLocationReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_da0d343210858f0d, []int{2}
}

func (m *UploadLocationReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UploadLocationReq.Unmarshal(m, b)
}
func (m *UploadLocationReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UploadLocationReq.Marshal(b, m, deterministic)
}
func (m *UploadLocationReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UploadLocationReq.Merge(m, src)
}
func (m *UploadLocationReq) XXX_Size() int {
	return xxx_messageInfo_UploadLocationReq.Size(m)
}
func (m *UploadLocationReq) XXX_DiscardUnknown() {
	xxx_messageInfo_UploadLocationReq.DiscardUnknown(m)
}

var xxx_messageInfo_UploadLocationReq proto.InternalMessageInfo

func (m *UploadLocationReq) GetClientId() string {
	if m != nil {
		return m.ClientId
	}
	return ""
}

func (m *UploadLocationReq) GetToClientId() string {
	if m != nil {
		return m.ToClientId
	}
	return ""
}

func (m *UploadLocationReq) GetAction() string {
	if m != nil {
		return m.Action
	}
	return ""
}

func (m *UploadLocationReq) GetWord() string {
	if m != nil {
		return m.Word
	}
	return ""
}

func init() {
	proto.RegisterType((*Rsponses)(nil), "protobuf.Rsponses")
	proto.RegisterType((*UploadReq)(nil), "protobuf.UploadReq")
	proto.RegisterType((*UploadLocationReq)(nil), "protobuf.UploadLocationReq")
}

func init() {
	proto.RegisterFile("robot_protobuf.proto", fileDescriptor_da0d343210858f0d)
}

var fileDescriptor_da0d343210858f0d = []byte{
	// 320 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0x4f, 0x4b, 0xfb, 0x40,
	0x10, 0xfd, 0xe5, 0xd7, 0x3f, 0x26, 0xd3, 0x22, 0x3a, 0x16, 0x59, 0x2a, 0x48, 0xc9, 0xa9, 0xa7,
	0x1e, 0xf4, 0xe4, 0xb9, 0x20, 0x14, 0x7a, 0xda, 0xea, 0x59, 0x36, 0xd9, 0xb1, 0x16, 0xd3, 0x6c,
	0xdd, 0xdd, 0x56, 0xc4, 0xcf, 0xe0, 0x67, 0x56, 0x32, 0x49, 0xfa, 0x47, 0xf1, 0xe8, 0x6d, 0xde,
	0x7b, 0x93, 0x97, 0xc7, 0xdb, 0x81, 0x9e, 0x35, 0x89, 0xf1, 0x0f, 0x2b, 0x6b, 0xbc, 0x49, 0xd6,
	0x8f, 0x23, 0x1e, 0x30, 0xac, 0x71, 0x7c, 0x0b, 0xa1, 0x74, 0x2b, 0x93, 0x3b, 0x72, 0x88, 0xd0,
	0x4c, 0x8d, 0x26, 0x11, 0x0c, 0x82, 0x61, 0x43, 0xf2, 0x8c, 0x27, 0xd0, 0x58, 0xba, 0xb9, 0xf8,
	0x3f, 0x08, 0x86, 0x91, 0x2c, 0x46, 0xec, 0x41, 0x6b, 0xe9, 0xe6, 0x13, 0x2d, 0x1a, 0xbc, 0x56,
	0x82, 0xf8, 0x33, 0x80, 0xe8, 0x7e, 0x95, 0x19, 0xa5, 0x25, 0xbd, 0x60, 0x1f, 0xc2, 0x34, 0x5b,
	0x50, 0xee, 0x27, 0x9a, 0xdd, 0x22, 0xb9, 0xc5, 0x78, 0x09, 0xe0, 0xcd, 0xb8, 0x56, 0x4b, 0xe3,
	0x3d, 0x06, 0xcf, 0xa1, 0xad, 0x52, 0xbf, 0x30, 0x39, 0xff, 0x20, 0x92, 0x15, 0x2a, 0x3c, 0x33,
	0x93, 0x2a, 0x56, 0x9a, 0xa5, 0x67, 0x8d, 0x71, 0x00, 0x9d, 0xf4, 0x49, 0xd9, 0x39, 0xcd, 0xbc,
	0xf2, 0x24, 0x5a, 0x9c, 0x6c, 0x9f, 0xc2, 0x18, 0xba, 0x89, 0xf2, 0x9e, 0xec, 0xdb, 0x94, 0x36,
	0x94, 0x89, 0x36, 0xaf, 0x1c, 0x70, 0xec, 0xb2, 0xb6, 0x96, 0x72, 0x7f, 0xa7, 0xdc, 0xb3, 0x38,
	0xaa, 0x5c, 0x76, 0x54, 0x91, 0x41, 0xd3, 0x66, 0x91, 0xd2, 0x44, 0x8b, 0x90, 0xe5, 0x2d, 0x8e,
	0xdf, 0xe1, 0xb4, 0x2c, 0x60, 0x5a, 0xa5, 0xfa, 0xab, 0x22, 0x10, 0x9a, 0xaf, 0xc6, 0xea, 0xaa,
	0x04, 0x9e, 0xaf, 0x3e, 0x02, 0xe8, 0xc8, 0xe2, 0xa5, 0x67, 0x64, 0x37, 0x64, 0x71, 0x0c, 0xc7,
	0x87, 0x61, 0xf0, 0x62, 0xb4, 0xbd, 0x81, 0x1f, 0x31, 0xfb, 0xb8, 0x13, 0xeb, 0x6b, 0x88, 0xff,
	0xe1, 0x0d, 0x74, 0xcb, 0xd5, 0xa2, 0xc2, 0xb5, 0xc3, 0xb3, 0xef, 0x16, 0xbf, 0x7e, 0x9a, 0xb4,
	0x99, 0xbc, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x1c, 0xc2, 0x8c, 0x7f, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// RobotServerClient is the client API for RobotServer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RobotServerClient interface {
	//查询终端是否在线
	//   rpc UsersOnline(UsersOnlineReq)returns(Rsponses){
	//   }
	//    //发送消息
	//    rpc SendMsg(SendMsgReq)returns(Rsponses) {
	//    }
	//    //发送视频邀请
	//    rpc StartCall(StartCallReq)returns(Rsponses){
	//     }
	//    //首页----去充电|去接待点|去指定地点|去巡逻|结束巡逻
	//    rpc ToAction(ToActionReq)returns(Rsponses){
	//    }
	//    //获取当前任务|机器人电量|当前位置|是否在线
	//    rpc GetIndexInfo(GetIndexInfoReq)returns(Rsponses){
	//    }
	UploadLocation(ctx context.Context, in *UploadLocationReq, opts ...grpc.CallOption) (*Rsponses, error)
	//上报机器人状态
	UploadStatus(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*Rsponses, error)
}

type robotServerClient struct {
	cc grpc.ClientConnInterface
}

func NewRobotServerClient(cc grpc.ClientConnInterface) RobotServerClient {
	return &robotServerClient{cc}
}

func (c *robotServerClient) UploadLocation(ctx context.Context, in *UploadLocationReq, opts ...grpc.CallOption) (*Rsponses, error) {
	out := new(Rsponses)
	err := c.cc.Invoke(ctx, "/protobuf.RobotServer/UploadLocation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *robotServerClient) UploadStatus(ctx context.Context, in *UploadReq, opts ...grpc.CallOption) (*Rsponses, error) {
	out := new(Rsponses)
	err := c.cc.Invoke(ctx, "/protobuf.RobotServer/UploadStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RobotServerServer is the server API for RobotServer service.
type RobotServerServer interface {
	UploadLocation(context.Context, *UploadLocationReq) (*Rsponses, error)
	//上报机器人状态
	UploadStatus(context.Context, *UploadReq) (*Rsponses, error)
}

// UnimplementedRobotServerServer can be embedded to have forward compatible implementations.
type UnimplementedRobotServerServer struct {
}

func (*UnimplementedRobotServerServer) UploadLocation(ctx context.Context, req *UploadLocationReq) (*Rsponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLocation not implemented")
}
func (*UnimplementedRobotServerServer) UploadStatus(ctx context.Context, req *UploadReq) (*Rsponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadStatus not implemented")
}

func RegisterRobotServerServer(s *grpc.Server, srv RobotServerServer) {
	s.RegisterService(&_RobotServer_serviceDesc, srv)
}

func _RobotServer_UploadLocation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadLocationReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServerServer).UploadLocation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RobotServer/UploadLocation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServerServer).UploadLocation(ctx, req.(*UploadLocationReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RobotServer_UploadStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RobotServerServer).UploadStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/protobuf.RobotServer/UploadStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RobotServerServer).UploadStatus(ctx, req.(*UploadReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _RobotServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protobuf.RobotServer",
	HandlerType: (*RobotServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadLocation",
			Handler:    _RobotServer_UploadLocation_Handler,
		},
		{
			MethodName: "UploadStatus",
			Handler:    _RobotServer_UploadStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "robot_protobuf.proto",
}
